### ISSUE TITLE
Feature : export - import vcard format

### ISSUE THREAD

**Issue by DriXse** [thierryvolpiatto/addressbook-bookmark#6]
Hi,
Is there a plan for a feature "import - export to vcard format" in the roadmap ?
Actually i use bbdb as main contact management, and then import into my android device.

Thanks.

**Comment by thierryvolpiatto** [comment]
DriXse <notifications@github.com> writes:

> Hi,
> Is there a plan for a feature "import - export to vcard format" in the roadmap ?
> Actually i use bbdb as main contact management, and then import into my android device.

Indeed it would be nice to have this, I will look into this as soon as I
have some time to do it.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
